# Prefix as Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# VI Mode
set -g mode-keys vi

set -g visual-activity on

# Enable Mouse
set -g mouse on

# New window on same dir
bind o new-window -c "#{pane_current_path}"

# No delay for Esc
set -s escape-time 0

# More friendly split pane
bind |  split-window -h -c '#{pane_current_path}'
bind \\ split-window -h -c '#{pane_current_path}'
bind -  split-window -v -c '#{pane_current_path}'

# Smart pane switching with awareness of Vim splits.
# Using christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\\ select-pane -l

bind-key j resize-pane -D 5 
bind-key k resize-pane -U 5 
bind-key h resize-pane -L 5 
bind-key l resize-pane -R 5

set-option -s set-clipboard on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se c -i"

bind-key -n C-Left  previous-window
bind-key -n C-Right next-window

bind-key -n C-Up copy-mode -eu

bind-key -n C-_ choose-tree -Z

# Kill windows and panes
bind q kill-pane
bind x confirm kill-window

bind n display-panes

# Reload settings
bind r source-file ~/.tmux.conf \; display "Settings reloaded!"
bind R respawn-pane -k

# Fix problems with st on nvim startup

# Visual
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

set -g window-style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=default'

set -g status-interval 5
set -g status-position bottom

# TokyoNight Storm — Clean Blocks

set -g mode-style "fg=#7aa2f7,bg=#3b4261"

set -g message-style "fg=#7aa2f7,bg=#3b4261"
set -g message-command-style "fg=#7aa2f7,bg=#3b4261"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

setw -g clock-mode-colour "#7aa2f7"

set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#7aa2f7,bg=#1f2335"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#7aa2f7,bg=default]#[fg=#15161E,bg=#7aa2f7,bold] #S #[fg=#7aa2f7,bg=default] "
set -g status-right "#(tmux-git-status)#[fg=#bb9af7,bg=default]#[fg=#15161E,bg=#bb9af7,bold] %m月%d日 #[fg=#bb9af7,bg=default] #[fg=#e0af68,bg=default]#[fg=#15161E,bg=#e0af68,bold] %H:%M #[fg=#e0af68,bg=default] #[fg=#7aa2f7,bg=default]#[fg=#15161E,bg=#7aa2f7,bold] #h #[fg=#7aa2f7,bg=default]"

setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=#1f2335"
setw -g window-status-separator " "
setw -g window-status-style "NONE,fg=#a9b1d6,bg=#1f2335"
setw -g window-status-current-style "NONE"
setw -g window-status-format "#[fg=#3b4261,bg=default]#[fg=#a9b1d6,bg=#3b4261] #I #W#[fg=#545a75]#F #[fg=#3b4261,bg=default]"
setw -g window-status-current-format "#[fg=#3b4261,bg=default]#[fg=#7aa2f7,bg=#3b4261,bold] #I #W#[fg=#e0af68]#F #[fg=#3b4261,bg=default]"

setw -g window-status-bell-style "fg=#f7768e,bg=#1f2335,bold"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-processes '"make dev",lazygit,lg,v,tail,less'

set-option -g history-limit 10000

# run '~/.tmux/plugins/tpm/tpm'
run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'
